name: CI

'on':
    pull_request:
    push:
        branches:
          - develop

env:
    UBSAN_OPTIONS: print_stacktrace=1

jobs:
    posix:
        strategy:
            fail-fast: false
            matrix:
                include:
                  - os: ubuntu-18.04
                    info: g++-9 + test-debug

                  - os: ubuntu-20.04
                    info: g++-9 + test-release

        name: '${{matrix.os}}: ${{matrix.info}}'
        runs-on: ${{matrix.os}}

        steps:
          - uses: actions/checkout@v2

          - name: Install packages
            run: |
                sudo apt install --allow-downgrades -y postgresql-12

          - name: Run psql 1
            run: |
            	sudo -u postgres psql --command="CREATE USER service_template PASSWORD 'service_template-password'" --command="\du"

          - name: Run psql 2
            run: |
            	sudo -u postgres createdb --owner=service_template service_template_table

          - name: Run psql 3
            run: |
            	PGPASSWORD=service_template-password psql 'postgresql://service_template@localhost:5432/service_template_table' --list service_template_table
                
